# Generated by Django 3.2.9 on 2021-11-19 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_no', models.IntegerField()),
                ('depart_dt', models.DateTimeField()),
                ('arrival_dt', models.DateTimeField()),
                ('depart_airport', models.CharField(max_length=120)),
                ('arrival_airport', models.CharField(max_length=120)),
            ],
        ),
    ]
